test 1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ env:
   REGION: us-east-1
   CLUSTER: my-eks-cluster
   URL: https://cdn.twistlock.com/releases/K8ABPUqE/prisma_cloud_compute_edition_22_06_197.tar.gz
-  CONSOLE_ADDRESS: https://us-east1.cloud.twistlock.com/us-1-111573457
+  CONSOLE_ADDRESS: us-east1.cloud.twistlock.com/us-1-111573457
   FOLDER: prisma_cloud_compute_edition_22_06_197
   KUBE_NAMESPACE: prod
 
@@ -56,19 +56,19 @@ jobs:
           mkdir prisma_cloud_compute_edition
 
           echo "----------------------------------------------------------------------"
-          echo "Downloading Prisma Cloud Compute tar file."
+          echo "Downloading twistcli"
 
           wget -O prisma_cloud_compute_edition.tar.gz -q $URL --no-check-certificate
 
           if [ $? == 0 ]
             then
               echo "----------------------------------------------------------------------"
-              echo "Successfully downloaded Prisma Cloud Compute tar file."
+              echo "Successfully downloaded twistcli."
               echo "----------------------------------------------------------------------"
               sleep 5
             else
               echo "----------------------------------------------------------------------"
-              echo "Failed to download Prisma Cloud Compute tar file."
+              echo "Failed to download twistcli."
               echo "----------------------------------------------------------------------"
               exit 1
             fi
@@ -76,6 +76,7 @@ jobs:
           tar xvzf prisma_cloud_compute_edition.tar.gz -C prisma_cloud_compute_edition/
 
           pwd
+          ls -l
 
       - name: Build Docker image
         run: |
@@ -89,7 +90,7 @@ jobs:
           cd ../prisma_cloud_compute_edition
           ./linux/twistcli images scan --address https://$CONSOLE_ADDRESS --user ${{ secrets.USER }} --password ${{ secrets.PASS }} --details ${{ steps.terraform.outputs.repo }}:${{ github.run_number }}
 
-          if [[ $? != 0 ]]
+          if [ $? != 0 ]
           then
             exit 1
           fi
